# Generated by Django 3.1.7 on 2021-03-18 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Civilian',
            fields=[
                ('hcc_no', models.IntegerField(primary_key=True, serialize=False)),
                ('phone_no', models.IntegerField()),
                ('sex', models.CharField(max_length=1)),
                ('address', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='DisposalSite',
            fields=[
                ('address', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('disposal_method', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('hcc_no', models.IntegerField(primary_key=True, serialize=False)),
                ('phone_no', models.IntegerField()),
                ('sex', models.CharField(max_length=1)),
                ('address', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('place_of_practice', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('hcc_no', models.IntegerField(primary_key=True, serialize=False)),
                ('phone_no', models.IntegerField()),
                ('sex', models.CharField(max_length=1)),
                ('address', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PpeSupplier',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('website', models.CharField(max_length=200)),
                ('contact_name', models.CharField(max_length=200)),
                ('contact_phone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='VaccinationSite',
            fields=[
                ('address', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('capacity', models.IntegerField()),
                ('contact_name', models.CharField(max_length=200)),
                ('contact_phone_no', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('DIN_no', models.IntegerField(primary_key=True, serialize=False)),
                ('disease_treated', models.CharField(max_length=200)),
                ('recommended_dose', models.CharField(max_length=200)),
                ('expiry_date', models.DateTimeField()),
                ('manufacturer_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RiskFactor',
            fields=[
                ('hcc_no', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='tracker.civilian')),
                ('location', models.CharField(max_length=200)),
                ('occupation', models.CharField(max_length=200)),
                ('at_risk_age', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='VaccineSideEffect',
            fields=[
                ('vaccine_side_effect_id', models.IntegerField(primary_key=True, serialize=False)),
                ('side_effect_name', models.CharField(max_length=200)),
                ('vaccine_DIN_no', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tracker.vaccine')),
            ],
        ),
        migrations.CreateModel(
            name='StoredAt',
            fields=[
                ('stored_at_id', models.IntegerField(primary_key=True, serialize=False)),
                ('temperature', models.FloatField(default=20)),
                ('humidity', models.FloatField(default=60)),
                ('lighting', models.FloatField(default=0)),
                ('DIN_no', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tracker.vaccine')),
                ('vaccination_site_address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tracker.vaccinationsite')),
            ],
        ),
        migrations.CreateModel(
            name='Ppe',
            fields=[
                ('ppe_id', models.IntegerField(primary_key=True, serialize=False)),
                ('is_disposable', models.BooleanField()),
                ('nurse_hcc', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tracker.nurse')),
                ('supplier_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tracker.ppesupplier')),
            ],
        ),
        migrations.AddField(
            model_name='nurse',
            name='site_address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tracker.vaccinationsite'),
        ),
        migrations.CreateModel(
            name='HealthCondition',
            fields=[
                ('health_condition_id', models.IntegerField(primary_key=True, serialize=False)),
                ('condition', models.CharField(max_length=200)),
                ('hcc_no', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tracker.civilian')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorCertification',
            fields=[
                ('doctor_certification_id', models.IntegerField(primary_key=True, serialize=False)),
                ('certification', models.CharField(max_length=200)),
                ('doctor_hcc_no', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tracker.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='DisposedAt',
            fields=[
                ('disposed_at_id', models.IntegerField(primary_key=True, serialize=False)),
                ('sharp', models.BooleanField(default=True)),
                ('biohazard_leakage', models.BooleanField(default=True)),
                ('DIN_no', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tracker.vaccine')),
                ('disposal_site_address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tracker.disposalsite')),
            ],
        ),
        migrations.AddField(
            model_name='civilian',
            name='doctor_hcc',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tracker.doctor'),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('appointment_id', models.IntegerField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField()),
                ('civilian_hcc_no', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tracker.civilian')),
                ('nurse_hcc_no', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tracker.nurse')),
                ('vaccination_site_address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tracker.vaccinationsite')),
                ('vaccine_DIN_no', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tracker.vaccine')),
            ],
        ),
        migrations.AddConstraint(
            model_name='vaccinesideeffect',
            constraint=models.UniqueConstraint(fields=('vaccine_DIN_no', 'side_effect_name'), name='VaccineSideEffect PK'),
        ),
        migrations.AddConstraint(
            model_name='storedat',
            constraint=models.UniqueConstraint(fields=('DIN_no', 'vaccination_site_address'), name='StoredAt PK'),
        ),
        migrations.AddConstraint(
            model_name='disposedat',
            constraint=models.UniqueConstraint(fields=('DIN_no', 'disposal_site_address'), name='DisposedAt PK'),
        ),
    ]
