# Generated by Django 3.1.7 on 2021-03-28 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_auto_20210323_2016'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='disposedat',
            name='DisposedAt PK',
        ),
        migrations.RemoveConstraint(
            model_name='storedat',
            name='StoredAt PK',
        ),
        migrations.RemoveConstraint(
            model_name='vaccinesideeffect',
            name='VaccineSideEffect PK',
        ),
    ]
