# Generated by Django 3.1.7 on 2021-03-28 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_auto_20210328_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='civilian',
            name='doctor_hcc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.doctor'),
        ),
        migrations.AlterField(
            model_name='disposedat',
            name='DIN_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.vaccine', verbose_name='Vaccine'),
        ),
        migrations.AlterField(
            model_name='disposedat',
            name='disposal_site_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.disposalsite'),
        ),
        migrations.AlterField(
            model_name='doctorcertification',
            name='doctor_hcc_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.doctor'),
        ),
        migrations.AlterField(
            model_name='healthcondition',
            name='hcc_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.civilian'),
        ),
        migrations.AlterField(
            model_name='nurse',
            name='site_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.vaccinationsite'),
        ),
        migrations.AlterField(
            model_name='ppe',
            name='nurse_hcc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.nurse', verbose_name='Assigned Nurse'),
        ),
        migrations.AlterField(
            model_name='ppe',
            name='supplier_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.ppesupplier', verbose_name='Supplier'),
        ),
        migrations.AlterField(
            model_name='riskfactor',
            name='hcc_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='tracker.civilian'),
        ),
        migrations.AlterField(
            model_name='storedat',
            name='DIN_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.vaccine', verbose_name='Vaccine'),
        ),
        migrations.AlterField(
            model_name='storedat',
            name='vaccination_site_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.vaccinationsite'),
        ),
        migrations.AlterField(
            model_name='vaccinesideeffect',
            name='vaccine_DIN_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.vaccine', verbose_name='Vaccine'),
        ),
    ]
