# Generated by Django 3.1.7 on 2021-03-28 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_auto_20210328_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='civilian_hcc_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.civilian'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='nurse_hcc_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.nurse'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='vaccination_site_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.vaccinationsite', verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='vaccine_DIN_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.vaccine', verbose_name='Vaccine'),
        ),
    ]
